import pandas as pd
import joblib


import pandas as pd

# df1=pd.read_csv("C:\\Users\\asus\\Downloads\\archive (5)\\Twitter_Data.csv")
#
# df2=pd.read_csv("C:\\Users\\asus\\Downloads\\archive (6)\\Reddit_Data.csv")
# df2=df2[['clean_comment','category']]
# df2=df2.rename(columns={'clean_comment':'clean_text'})
#
# df3=pd.read_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis1.csv",encoding='ISO-8859-1')
# df3=df3.rename(columns={'text':'clean_text',"sentiment":"category"})
# df3=df3[['clean_text','category']]
# df3['category']=df3['category'].replace({"positive":1,"negative":-1,"neutral":0})
#
# df4=pd.read_csv("C:\\Users\\asus\\Downloads\\trainingandtestdata\\training.1600000.processed.noemoticon.csv",encoding='ISO-8859-1')
# df4 = df4.rename(columns={'0': 'Label',
#                         "@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D": 'Text',
#                         "1467810369":"ID",
#                          "Mon Apr 06 22:19:45 PDT 2009":"Date&Time",
#                          "_TheSpecialOne_":"User",
#                          "NO_QUERY":"Flag"})
# df4=df4.rename(columns={'Text':'clean_text',"Label":"category"})
# df4=df4[['clean_text','category']]
# df4['category']=df4['category'].replace({4:1,0:-1})
#
# df5=pd.read_csv("C:\\Users\\asus\\Downloads\\archive (7)\\SFU_Corpus.csv")
# df5=df5.rename(columns={'sentence':'clean_text',"target":"category"})
#
#
# df6=pd.read_csv("C:\\Users\\asus\\Downloads\\negation_dataset.csv")
#
# df7=pd.read_csv("C:\\Users\\asus\\Downloads\\negation_dataset_large.csv")
#
# df8=pd.read_csv("C:\\Users\\asus\\Downloads\\negation_sentiment_100k.csv")
# df8=df8.rename(columns={'text':'clean_text',"sentiment":"category"})
#
# df9=pd.read_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis_dataset.csv")
# df9=df9.rename(columns={'text':'clean_text',"sentiment":"category"})
#
#
# df10=pd.read_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis_dataset_1.csv")
# df10=df10.rename(columns={'text':'clean_text',"sentiment":"category"})
#
# df11=pd.read_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis_dataset_2.csv")
# df11=df11.rename(columns={'text':'clean_text',"sentiment":"category"})
#
# df12=pd.read_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis_dataset_3.csv")
# df12=df12.rename(columns={'text':'clean_text',"sentiment":"category"})
#
# df13=pd.read_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis_dataset_4.csv")
# df13=df13.rename(columns={'text':'clean_text',"sentiment":"category"})
#
# df14=pd.read_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis_dataset_5.csv")
# df14=df14.rename(columns={'text':'clean_text',"sentiment":"category"})
#
# df15=pd.read_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis_dataset_6.csv")
# df15=df15.rename(columns={'text':'clean_text',"sentiment":"category"})
#
# df16=pd.read_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis_dataset_7.csv")
# df16=df16.rename(columns={'text':'clean_text',"sentiment":"category"})
#
# df17=pd.read_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis_dataset_8.csv")
# df17=df17.rename(columns={'text':'clean_text',"sentiment":"category"})
#
# df18=pd.read_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis_dataset_9.csv")
# df18=df18.rename(columns={'text':'clean_text',"sentiment":"category"})
#
# df19=pd.read_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis_dataset_10.csv")
# df19=df19.rename(columns={'text':'clean_text',"sentiment":"category"})
#
# df20=pd.read_csv("C:\\Users\\asus\\Downloads\\train_all.csv")
# df20=df20.rename(columns={'sentence':'clean_text',"label":"category"})
# df20=df20[['clean_text','category']]
# df20['category']=df20['category'].replace({"positive":1,"negative":-1,"neutral":0})
#
# df22=pd.read_csv("C:\\Users\\asus\\Downloads\\test_all.csv")
# df22=df22.rename(columns={'sentence':'clean_text',"label":"category"})
# df22=df22[['clean_text','category']]
# df22['category']=df22['category'].replace({"positive":1,"negative":-1,"neutral":0})
#
# df21=pd.read_csv("C:\\Users\\asus\\Downloads\\IMDB Dataset.csv")
# df21=df21.rename(columns={'review':'clean_text',"sentiment":"category"})
# df21=df21[['clean_text','category']]
# df21['category']=df21['category'].replace({"positive":1,"negative":-1,"neutral":0})
#
#
# additional_data = pd.DataFrame([
#     {"clean_text": "The patient's condition remains stable for now.", "category": 0},
#     {"clean_text": "The hospital staff is following standard procedures.", "category": 0},
#     {"clean_text": "The new medication is being tested for effectiveness.", "category": 0},
#     {"clean_text": "The healthcare facility is undergoing routine maintenance.", "category": 0},
#     {"clean_text": "The doctor's diagnosis is still under review.", "category": 0},
#     {"clean_text": "The patient is currently under observation.", "category": 0},
#     {"clean_text": "The medical equipment is being inspected for issues.", "category": 0},
#     {"clean_text": "The treatment plan is being adjusted as needed.", "category": 0},
#     {"clean_text": "The healthcare costs are being discussed by the board.", "category": 0},
#     {"clean_text": "The hospital is implementing new hygiene protocols.", "category": 0},
#     {"clean_text": "The software update is being rolled out gradually.", "category": 0},
#     {"clean_text": "The app is being tested for usability improvements.", "category": 0},
#     {"clean_text": "The new feature is still in the development phase.", "category": 0},
#     {"clean_text": "The device is being evaluated for durability.", "category": 0},
#     {"clean_text": "The company is reviewing customer feedback.", "category": 0},
#     {"clean_text": "The product is being compared to competitors.", "category": 0},
#     {"clean_text": "The system is being updated for better security.", "category": 0},
#     {"clean_text": "The performance is being monitored for improvements.", "category": 0},
#     {"clean_text": "The interface is being redesigned for better usability.", "category": 0},
#     {"clean_text": "The battery life is being tested under various conditions.", "category": 0},
#     {"clean_text": "The curriculum is being revised to meet modern standards.", "category": 0},
#     {"clean_text": "The teacher is attending a training workshop.", "category": 0},
#     {"clean_text": "The exam results are being analyzed for trends.", "category": 0},
#     {"clean_text": "The school is considering additional resources.", "category": 0},
#     {"clean_text": "The online learning platform is being upgraded.", "category": 0},
#     {"clean_text": "The course material is being updated for relevance.", "category": 0},
#     {"clean_text": "The feedback from students is being collected.", "category": 0},
#     {"clean_text": "The program is being evaluated for effectiveness.", "category": 0},
#     {"clean_text": "The classroom environment is being assessed.", "category": 0},
#     {"clean_text": "The grading system is being reviewed for fairness.", "category": 0},
#     {"clean_text": "The team is practicing for the upcoming tournament.", "category": 0},
#     {"clean_text": "The player is recovering from a minor injury.", "category": 0},
#     {"clean_text": "The coach is analyzing the opponent's strategy.", "category": 0},
#     {"clean_text": "The training facilities are being renovated.", "category": 0},
#     {"clean_text": "The match is scheduled for next week.", "category": 0},
#     {"clean_text": "The referee's decisions are being reviewed.", "category": 0},
#     {"clean_text": "The team spirit is being encouraged by the coach.", "category": 0},
#     {"clean_text": "The injury is being monitored by the medical team.", "category": 0},
#     {"clean_text": "The fans are waiting for the next game.", "category": 0},
#     {"clean_text": "The strategy is being adjusted for the next match.", "category": 0},
#     {"clean_text": "The stock market is showing mixed trends.", "category": 0},
#     {"clean_text": "The investment is being reviewed for potential returns.", "category": 0},
#     {"clean_text": "The bank is considering new interest rate policies.", "category": 0},
#     {"clean_text": "The financial report is being prepared for release.", "category": 0},
#     {"clean_text": "The company is analyzing its quarterly performance.", "category": 0},
#     {"clean_text": "The loan approval process is being streamlined.", "category": 0},
#     {"clean_text": "The economy is being monitored for signs of recovery.", "category": 0},
#     {"clean_text": "The budget is being finalized for the next fiscal year.", "category": 0},
#     {"clean_text": "The financial advisor is reviewing the client's portfolio.", "category": 0},
#     {"clean_text": "The revenue growth is being analyzed for sustainability.", "category": 0},
#     {"clean_text": "The movie is being promoted for its unique storyline.", "category": 0},
#     {"clean_text": "The plot is being discussed by critics.", "category": 0},
#     {"clean_text": "The acting is being praised by some viewers.", "category": 0},
#     {"clean_text": "The soundtrack is being released as a separate album.", "category": 0},
#     {"clean_text": "The special effects are being highlighted in the trailer.", "category": 0},
#     {"clean_text": "The show is being considered for a second season.", "category": 0},
#     {"clean_text": "The comedy is being appreciated by a niche audience.", "category": 0},
#     {"clean_text": "The storyline is being adapted from a popular book.", "category": 0},
#     {"clean_text": "The performance is being reviewed by critics.", "category": 0},
#     {"clean_text": "The reviews are being compiled for a final rating.", "category": 0},
#     {"clean_text": "The movie is not entertaining.", "category": -1},
#     {"clean_text": "The plot is not engaging.", "category": -1},
#     {"clean_text": "The acting is not impressive.", "category": -1},
#     {"clean_text": "The soundtrack is not memorable.", "category": -1},
#     {"clean_text": "The special effects are not realistic.", "category": -1},
#     {"clean_text": "The show is not worth watching.", "category": -1},
#     {"clean_text": "The comedy is not funny.", "category": -1},
#     {"clean_text": "The storyline is not original.", "category": -1},
#     {"clean_text": "The performance is not captivating.", "category": -1},
#     {"clean_text": "The reviews are not positive.", "category": -1},
#     {"clean_text": "The policy is not effective.", "category": -1},
#     {"clean_text": "The government is not transparent.", "category": -1},
#     {"clean_text": "The decision is not in the public's interest.", "category": -1},
#     {"clean_text": "The election process is not fair.", "category": -1},
#     {"clean_text": "The leader is not trustworthy.", "category": -1},
#     {"clean_text": "The reforms are not impactful.", "category": -1},
#     {"clean_text": "The opposition is not constructive.", "category": -1},
#     {"clean_text": "The campaign is not well-organized.", "category": -1},
#     {"clean_text": "The public opinion is not favorable.", "category": -1},
#     {"clean_text": "The legislation is not progressive.", "category": -1},
#     {"clean_text": "The flight is not on time.", "category": -1},
#     {"clean_text": "The hotel service is not satisfactory.", "category": -1},
#     {"clean_text": "The destination is not as expected.", "category": -1},
#     {"clean_text": "The travel experience is not enjoyable.", "category": -1},
#     {"clean_text": "The transportation is not reliable.", "category": -1},
#     {"clean_text": "The tour guide is not knowledgeable.", "category": -1},
#     {"clean_text": "The accommodation is not comfortable.", "category": -1},
#     {"clean_text": "The itinerary is not well-planned.", "category": -1},
#     {"clean_text": "The food options are not diverse.", "category": -1},
#     {"clean_text": "The weather is not pleasant.", "category": -1},
#     {"clean_text": "The dish is not flavorful.", "category": -1},
#     {"clean_text": "The service is not prompt.", "category": -1},
#     {"clean_text": "The ingredients are not fresh.", "category": -1},
#     {"clean_text": "The portion size is not adequate.", "category": -1},
#     {"clean_text": "The restaurant is not clean.", "category": -1},
#     {"clean_text": "The menu is not diverse.", "category": -1},
#     {"clean_text": "The presentation is not appealing.", "category": -1},
#     {"clean_text": "The taste is not authentic.", "category": -1},
#     {"clean_text": "The wait time is not reasonable.", "category": -1},
#     {"clean_text": "The prices are not affordable.", "category": -1},
#     {"clean_text": "The stock market is not performing well.", "category": -1},
#     {"clean_text": "The investment is not yielding good returns.", "category": -1},
#     {"clean_text": "The economy is not recovering as expected.", "category": -1},
#     {"clean_text": "The budget is not well-planned.", "category": -1},
#     {"clean_text": "The financial report is not accurate.", "category": -1},
#     {"clean_text": "The company is not profitable this quarter.", "category": -1},
#     {"clean_text": "The interest rates are not favorable.", "category": -1},
#     {"clean_text": "The loan approval process is not efficient.", "category": -1},
#     {"clean_text": "The financial stability is not guaranteed.", "category": -1},
#     {"clean_text": "The revenue growth is not sustainable.", "category": -1},
#     {"clean_text": "The product is not overpriced.", "category": 1},
#     {"clean_text": "I am not dissatisfied with the service.", "category": 1},
#     {"clean_text": "This is not a waste of money.", "category": 1},
#     {"clean_text": "I am not unhappy with the purchase.", "category": 1},
#     {"clean_text": "The delivery was not delayed.", "category": 1},
#     {"clean_text": "I am not regretting this choice.", "category": 1},
#     {"clean_text": "This is not a bad investment.", "category": 1},
#     {"clean_text": "I am not frustrated with the results.", "category": 1},
#     {"clean_text": "The experience was not unpleasant.", "category": 1},
#     {"clean_text": "I am not disappointed in the quality.", "category": 1},
#     {"clean_text": "This is not a poor decision.", "category": 1},
#     {"clean_text": "I am not upset with the outcome.", "category": 1},
#     {"clean_text": "The product is not faulty.", "category": 1},
#     {"clean_text": "I am not annoyed by the service.", "category": 1},
#     {"clean_text": "This is not a negative experience.", "category": 1},
#     {"clean_text": "I am not unhappy with the delivery.", "category": 1},
#     {"clean_text": "The performance is not subpar.", "category": 1},
#     {"clean_text": "I am not dissatisfied with the product.", "category": 1},
#     {"clean_text": "This is not a letdown at all.", "category": 1},
#     {"clean_text": "I am not displeased with the results.", "category": 1},
#     {"clean_text": "The quality is not below average.", "category": 1},
#     {"clean_text": "I am not bothered by the experience.", "category": 1},
#     {"clean_text": "This is not a mistake on their part.", "category": 1},
#     {"clean_text": "I am not unhappy with the service provided.", "category": 1},
#     {"clean_text": "The product is not of low quality.", "category": 1},
#     {"clean_text": "I am not dissatisfied with the purchase.", "category": 1},
#     {"clean_text": "This is not a bad experience at all.", "category": 1},
#     {"clean_text": "I am not upset with the service.", "category": 1},
#     {"clean_text": "The outcome is not disappointing.", "category": 1},
#     {"clean_text": "I am not regretting this purchase.", "category": 1},
#     {"clean_text": "This is not a failure on their part.", "category": 1},
#     {"clean_text": "I am not angry with the service.", "category": 1},
#     {"clean_text": "The product is not poorly made.", "category": 1},
#     {"clean_text": "I am not frustrated with the delivery.", "category": 1},
#     {"clean_text": "This is not a letdown in any way.", "category": 1},
#     {"clean_text": "I am not annoyed with the results.", "category": 1},
#     {"clean_text": "The experience is not negative at all.", "category": 1},
#     {"clean_text": "I am not unhappy with the quality.", "category": 1},
#     {"clean_text": "This is not a disappointment at all.", "category": 1},
#     {"clean_text": "I am not displeased with the service.", "category": 1},
#     {"clean_text": "I am not happy.", "category": -1},
#     {"clean_text": "This is not bad.", "category": 1},
#     {"clean_text": "The service was not good.", "category": -1},
#     {"clean_text": "I cannot recommend this.", "category": -1},
#     {"clean_text": "This is not the best.", "category": -1},
#     {"clean_text": "I am not disappointed.", "category": 1},
#     {"clean_text": "This is not terrible.", "category": 1},
#     {"clean_text": "I am not impressed.", "category": -1},
#     {"clean_text": "The product is not worth the price.", "category": -1},
#     {"clean_text": "I am not satisfied with the results.", "category": -1},
#     {"clean_text": "This is not what I expected.", "category": -1},
#     {"clean_text": "The food was not tasty.", "category": -1},
#     {"clean_text": "I am not sure if I like this.", "category": 0},
#     {"clean_text": "This is not a problem.", "category": 1},
#     {"clean_text": "I am not unhappy with the service.", "category": 1},
#     {"clean_text": "The movie was not boring.", "category": 1},
#     {"clean_text": "I am not against this idea.", "category": 1},
#     {"clean_text": "This is not a waste of time.", "category": 1},
#     {"clean_text": "I am not feeling well.", "category": -1},
#     {"clean_text": "The weather is not great today.", "category": -1},
#     {"clean_text": "I am not a fan of this.", "category": -1},
#     {"clean_text": "This is not the worst thing ever.", "category": 1},
#     {"clean_text": "I am not convinced this will work.", "category": -1},
#     {"clean_text": "The performance was not up to the mark.", "category": -1},
#     {"clean_text": "I am not ready for this.", "category": -1},
#     {"clean_text": "This is not my favorite.", "category": -1},
#     {"clean_text": "I am not in the mood for this.", "category": -1},
#     {"clean_text": "The experience was not pleasant.", "category": -1},
#     {"clean_text": "I am not going to buy this again.", "category": -1},
#     {"clean_text": "This is not a good deal.", "category": -1},
#     {"clean_text": "I am not sure if this is worth it.", "category": 0},
#     {"clean_text": "The quality is not poor.", "category": 1},
#     {"clean_text": "I am not complaining.", "category": 1},
#     {"clean_text": "This is not a big issue.", "category": 1},
#     {"clean_text": "I am not worried about it.", "category": 1},
#     {"clean_text": "The outcome is not bad.", "category": 1},
#     {"clean_text": "I am not sad about the decision.", "category": 1},
#     {"clean_text": "This is not the end of the world.", "category": 1},
#     {"clean_text": "I am not giving up.", "category": 1},
#     {"clean_text": "The situation is not hopeless.", "category": 1},
#     {"clean_text": "This is not a bad experience.", "category": 1},
#     {"clean_text": "I am not upset about it.", "category": 1},
#     {"clean_text": "The result is not disappointing.", "category": 1},
#     {"clean_text": "This is not a failure.", "category": 1},
#     {"clean_text": "I am not angry with the outcome.", "category": 1},
#     {"clean_text": "The product is not defective.", "category": 1},
#     {"clean_text": "I am not frustrated.", "category": 1},
#     {"clean_text": "This is not a letdown.", "category": 1},
#     {"clean_text": "I am not annoyed.", "category": 1},
#     {"clean_text": "The service is not slow.", "category": 1},
#     {"clean_text": "I am not dissatisfied.", "category": 1},
#     {"clean_text": "This is not a scam.", "category": 1},
#     {"clean_text": "I am not regretting my decision.", "category": 1},
#     {"clean_text": "The experience is not negative.", "category": 1},
#     {"clean_text": "I am not unhappy with the product.", "category": 1},
#     {"clean_text": "This is not a disappointment.", "category": 1},
#     {"clean_text": "I am not displeased.", "category": 1},
#     {"clean_text": "The quality is not low.", "category": 1},
#     {"clean_text": "I am not bothered by it.", "category": 1},
#     {"clean_text": "This is not a mistake.", "category": 1},
#     {"clean_text": "The patient is not showing signs of improvement.", "category": -1},
#     {"clean_text": "The treatment is not effective for this condition.", "category": -1},
#     {"clean_text": "The medication is not causing any side effects.", "category": 1},
#     {"clean_text": "The diagnosis is not clear yet.", "category": 0},
#     {"clean_text": "The recovery process is not progressing as expected.", "category": -1},
#     {"clean_text": "The surgery was not successful.", "category": -1},
#     {"clean_text": "The patient is not in critical condition.", "category": 1},
#     {"clean_text": "The healthcare provider is not responsive.", "category": -1},
#     {"clean_text": "The treatment plan is not well-defined.", "category": -1},
#     {"clean_text": "The patient is not experiencing any pain.", "category": 1},
#     {"clean_text": "The software is not functioning properly.", "category": -1},
#     {"clean_text": "The update is not causing any issues.", "category": 1},
#     {"clean_text": "The device is not compatible with the system.", "category": -1},
#     {"clean_text": "The app is not user-friendly.", "category": -1},
#     {"clean_text": "The feature is not working as intended.", "category": -1},
#     {"clean_text": "The performance is not up to expectations.", "category": -1},
#     {"clean_text": "The security patch is not effective.", "category": -1},
#     {"clean_text": "The product is not innovative.", "category": -1},
#     {"clean_text": "The system is not crashing anymore.", "category": 1},
#     {"clean_text": "The interface is not intuitive.", "category": -1},
#     {"clean_text": "The course material is not comprehensive.", "category": -1},
#     {"clean_text": "The instructor is not engaging.", "category": -1},
#     {"clean_text": "The exam results are not satisfactory.", "category": -1},
#     {"clean_text": "The curriculum is not up-to-date.", "category": -1},
#     {"clean_text": "The learning resources are not accessible.", "category": -1},
#     {"clean_text": "The program is not well-structured.", "category": -1},
#     {"clean_text": "The feedback is not constructive.", "category": -1},
#     {"clean_text": "The student performance is not improving.", "category": -1},
#     {"clean_text": "The online platform is not reliable.", "category": -1},
#     {"clean_text": "The course is not challenging enough.", "category": -1},
#     {"clean_text": "The team is not performing well this season.", "category": -1},
#     {"clean_text": "The player is not in top form.", "category": -1},
#     {"clean_text": "The match was not exciting.", "category": -1},
#     {"clean_text": "The coach is not making the right decisions.", "category": -1},
#     {"clean_text": "The training regimen is not effective.", "category": -1},
#     {"clean_text": "The injury is not serious.", "category": 1},
#     {"clean_text": "The strategy is not working.", "category": -1},
#     {"clean_text": "The fans are not satisfied with the performance.", "category": -1},
#     {"clean_text": "The referee is not fair.", "category": -1},
#     {"clean_text": "The team spirit is not high.", "category": -1},
#     {"clean_text": "The pollution levels are not decreasing.", "category": -1},
#     {"clean_text": "The conservation efforts are not effective.", "category": -1},
#     {"clean_text": "The climate change impact is not negligible.", "category": -1},
#     {"clean_text": "The wildlife is not thriving in this area.", "category": -1},
#     {"clean_text": "The recycling program is not well-implemented.", "category": -1},
#     {"clean_text": "The air quality is not improving.", "category": -1},
#     {"clean_text": "The deforestation rate is not slowing down.", "category": -1},
#     {"clean_text": "The ecosystem is not balanced.", "category": -1},
#     {"clean_text": "The environmental policies are not strict enough.", "category": -1},
#     {"clean_text": "The natural resources are not being conserved.", "category": -1},
#     {"clean_text": "The patient's condition is not improving despite treatment.", "category": -1},
#     {"clean_text": "The hospital staff is not responding to emergencies quickly.", "category": -1},
#     {"clean_text": "The new medication is not causing any adverse effects.", "category": 1},
#     {"clean_text": "The healthcare facility is not well-maintained.", "category": -1},
#     {"clean_text": "The doctor's diagnosis is not accurate.", "category": -1},
#     {"clean_text": "The patient is not recovering as expected.", "category": -1},
#     {"clean_text": "The medical equipment is not functioning properly.", "category": -1},
#     {"clean_text": "The treatment plan is not effective for the patient.", "category": -1},
#     {"clean_text": "The healthcare costs are not affordable for most people.", "category": -1},
#     {"clean_text": "The hospital is not following proper hygiene protocols.", "category": -1},
#     {"clean_text": "The software update is not compatible with older devices.", "category": -1},
#     {"clean_text": "The app is not user-friendly for beginners.", "category": -1},
#     {"clean_text": "The new feature is not working as advertised.", "category": -1},
#     {"clean_text": "The device is not durable enough for daily use.", "category": -1},
#     {"clean_text": "The company is not addressing customer complaints.", "category": -1},
#     {"clean_text": "The product is not innovative compared to competitors.", "category": -1},
#     {"clean_text": "The system is not secure against cyber threats.", "category": -1},
#     {"clean_text": "The performance is not up to industry standards.", "category": -1},
#     {"clean_text": "The interface is not intuitive for new users.", "category": -1},
#     {"clean_text": "The battery life is not sufficient for heavy usage.", "category": -1},
#     {"clean_text": "The curriculum is not aligned with modern standards.", "category": -1},
#     {"clean_text": "The teacher is not engaging with students effectively.", "category": -1},
#     {"clean_text": "The exam results are not reflecting the students' abilities.", "category": -1},
#     {"clean_text": "The school is not providing adequate resources.", "category": -1},
#     {"clean_text": "The online learning platform is not reliable.", "category": -1},
#     {"clean_text": "The course material is not up-to-date.", "category": -1},
#     {"clean_text": "The feedback from students is not being considered.", "category": -1},
#     {"clean_text": "The program is not preparing students for real-world challenges.", "category": -1},
#     {"clean_text": "The classroom environment is not conducive to learning.", "category": -1},
#     {"clean_text": "The grading system is not fair to all students.", "category": -1},
#     {"clean_text": "The team is not performing well in the tournament.", "category": -1},
#     {"clean_text": "The player is not meeting expectations this season.", "category": -1},
#     {"clean_text": "The coach is not making strategic decisions.", "category": -1},
#     {"clean_text": "The training facilities are not up to standard.", "category": -1},
#     {"clean_text": "The match was not exciting for the fans.", "category": -1},
#     {"clean_text": "The referee's decisions are not fair.", "category": -1},
#     {"clean_text": "The team spirit is not high among players.", "category": -1},
#     {"clean_text": "The injury is not affecting the player's performance.", "category": 1},
#     {"clean_text": "The fans are not satisfied with the team's performance.", "category": -1},
#     {"clean_text": "The strategy is not working against strong opponents.", "category": -1},
#     {"clean_text": "The stock market is not stable this quarter.", "category": -1},
#     {"clean_text": "The investment is not yielding expected returns.", "category": -1},
#     {"clean_text": "The bank is not offering competitive interest rates.", "category": -1},
#     {"clean_text": "The financial report is not transparent.", "category": -1},
#     {"clean_text": "The company is not profitable this year.", "category": -1},
#     {"clean_text": "The loan approval process is not efficient.", "category": -1},
#     {"clean_text": "The economy is not recovering as predicted.", "category": -1},
#     {"clean_text": "The budget is not well-planned for the fiscal year.", "category": -1},
#     {"clean_text": "The financial advisor is not providing good recommendations.", "category": -1},
#     {"clean_text": "The revenue growth is not sustainable in the long term.", "category": -1},
#     {"clean_text": "The movie is not living up to the hype.", "category": -1},
#     {"clean_text": "The plot is not engaging for the audience.", "category": -1},
#     {"clean_text": "The acting is not convincing in this film.", "category": -1},
#     {"clean_text": "The soundtrack is not memorable for this movie.", "category": -1},
#     {"clean_text": "The special effects are not realistic in this film.", "category": -1},
#     {"clean_text": "The show is not worth the subscription fee.", "category": -1},
#     {"clean_text": "The comedy is not funny for most viewers.", "category": -1},
#     {"clean_text": "The storyline is not original in this series.", "category": -1},
#     {"clean_text": "The performance is not captivating in this play.", "category": -1},
#     {"clean_text": "The reviews are not positive for this production.", "category": -1},
#     {"clean_text": "The patient's recovery is progressing as expected.", "category": 1},
#     {"clean_text": "The hospital staff is highly professional and responsive.", "category": 1},
#     {"clean_text": "The new medication has shown promising results.", "category": 1},
#     {"clean_text": "The healthcare facility is clean and well-organized.", "category": 1},
#     {"clean_text": "The doctor's diagnosis was accurate and thorough.", "category": 1},
#     {"clean_text": "The patient is responding well to the treatment.", "category": 1},
#     {"clean_text": "The medical equipment is state-of-the-art.", "category": 1},
#     {"clean_text": "The treatment plan is tailored to the patient's needs.", "category": 1},
#     {"clean_text": "The healthcare costs are reasonable and transparent.", "category": 1},
#     {"clean_text": "The hospital follows strict hygiene protocols.", "category": 1},
#     {"clean_text": "The software update has improved performance significantly.", "category": 1},
#     {"clean_text": "The app is intuitive and easy to use.", "category": 1},
#     {"clean_text": "The new feature has been well-received by users.", "category": 1},
#     {"clean_text": "The device is durable and reliable.", "category": 1},
#     {"clean_text": "The company values customer feedback and acts on it.", "category": 1},
#     {"clean_text": "The product stands out among competitors.", "category": 1},
#     {"clean_text": "The system is secure and regularly updated.", "category": 1},
#     {"clean_text": "The performance exceeds industry standards.", "category": 1},
#     {"clean_text": "The interface is user-friendly and visually appealing.", "category": 1},
#     {"clean_text": "The battery life is impressive for heavy usage.", "category": 1},
#     {"clean_text": "The curriculum is comprehensive and up-to-date.", "category": 1},
#     {"clean_text": "The teacher is passionate and engaging.", "category": 1},
#     {"clean_text": "The exam results reflect the students' hard work.", "category": 1},
#     {"clean_text": "The school provides excellent resources for students.", "category": 1},
#     {"clean_text": "The online learning platform is reliable and efficient.", "category": 1},
#     {"clean_text": "The course material is relevant and well-structured.", "category": 1},
#     {"clean_text": "The feedback from students is taken seriously.", "category": 1},
#     {"clean_text": "The program prepares students for real-world challenges.", "category": 1},
#     {"clean_text": "The classroom environment is supportive and inclusive.", "category": 1},
#     {"clean_text": "The grading system is fair and transparent.", "category": 1},
#     {"clean_text": "The team is performing exceptionally well this season.", "category": 1},
#     {"clean_text": "The player is in excellent form and delivering results.", "category": 1},
#     {"clean_text": "The coach is making strategic and effective decisions.", "category": 1},
#     {"clean_text": "The training facilities are top-notch.", "category": 1},
#     {"clean_text": "The match was thrilling and kept fans on the edge.", "category": 1},
#     {"clean_text": "The referee's decisions were fair and unbiased.", "category": 1},
#     {"clean_text": "The team spirit is high and motivating.", "category": 1},
#     {"clean_text": "The injury is being managed effectively by the medical team.", "category": 1},
#     {"clean_text": "The fans are excited and supportive of the team.", "category": 1},
#     {"clean_text": "The strategy is working well against strong opponents.", "category": 1},
#     {"clean_text": "The stock market is showing positive trends.", "category": 1},
#     {"clean_text": "The investment is yielding excellent returns.", "category": 1},
#     {"clean_text": "The bank offers competitive interest rates.", "category": 1},
#     {"clean_text": "The financial report is transparent and detailed.", "category": 1},
#     {"clean_text": "The company is profitable and growing steadily.", "category": 1},
#     {"clean_text": "The loan approval process is quick and efficient.", "category": 1},
#     {"clean_text": "The economy is recovering faster than expected.", "category": 1},
#     {"clean_text": "The budget is well-planned and balanced.", "category": 1},
#     {"clean_text": "The financial advisor provides excellent recommendations.", "category": 1},
#     {"clean_text": "The revenue growth is sustainable and impressive.", "category": 1},
#     {"clean_text": "The movie is entertaining and worth watching.", "category": 1},
#     {"clean_text": "The plot is engaging and keeps the audience hooked.", "category": 1},
#     {"clean_text": "The acting is impressive and convincing.", "category": 1},
#     {"clean_text": "The soundtrack is memorable and enhances the movie.", "category": 1},
#     {"clean_text": "The special effects are realistic and stunning.", "category": 1},
#     {"clean_text": "The show is worth the subscription fee.", "category": 1},
#     {"clean_text": "The comedy is hilarious and well-executed.", "category": 1},
#     {"clean_text": "The storyline is original and refreshing.", "category": 1},
#     {"clean_text": "The performance is captivating and emotional.", "category": 1},
#     {"clean_text": "The reviews are overwhelmingly positive.", "category": 1},
#     {"clean_text": "The policy is effective and well-implemented.", "category": 1},
#     {"clean_text": "The government is transparent and accountable.", "category": 1},
#     {"clean_text": "The decision is in the public's best interest.", "category": 1},
#     {"clean_text": "The election process is fair and democratic.", "category": 1},
#     {"clean_text": "The leader is trustworthy and competent.", "category": 1},
#     {"clean_text": "The reforms are impactful and transformative.", "category": 1},
#     {"clean_text": "The opposition is constructive and collaborative.", "category": 1},
#     {"clean_text": "The campaign is well-organized and effective.", "category": 1},
#     {"clean_text": "The public opinion is favorable and supportive.", "category": 1},
#     {"clean_text": "The legislation is progressive and inclusive.", "category": 1},
#     {"clean_text": "The flight is on time and comfortable.", "category": 1},
#     {"clean_text": "The hotel service is excellent and attentive.", "category": 1},
#     {"clean_text": "The destination is beautiful and relaxing.", "category": 1},
#     {"clean_text": "The test results are not available yet.", "category": 0},
#     {"clean_text": "The hospital is not following safety protocols.", "category": -1},
#     {"clean_text": "The procedure is not expected to have complications.", "category": 1},
#     {"clean_text": "The symptoms are not improving after medication.", "category": -1},
#     {"clean_text": "The doctor is not available today.", "category": 0},
#     {"clean_text": "The condition is not life-threatening.", "category": 1},
#     {"clean_text": "The report is not complete.", "category": 0},
#     {"clean_text": "The test is not showing consistent results.", "category": -1},
#     {"clean_text": "The patient is not at risk of infection.", "category": 1},
#     {"clean_text": "The prescription is not clearly written.", "category": -1},
#     {"clean_text": "The equipment is not functioning as expected.", "category": -1},
#     {"clean_text": "The recovery time is not longer than expected.", "category": 1},
#     {"clean_text": "The symptoms are not severe at the moment.", "category": 1},
#     {"clean_text": "The laboratory is not meeting deadlines.", "category": -1},
#     {"clean_text": "The test results are not alarming.", "category": 1},
#     {"clean_text": "The procedure is not covered by insurance.", "category": -1},
#     {"clean_text": "The patient is not following the diet plan.", "category": -1},
#     {"clean_text": "The results are not conclusive.", "category": 0},
#     {"clean_text": "The side effects are not dangerous.", "category": 1},
#     {"clean_text": "The surgery is not scheduled for tomorrow.", "category": 0},
#     {"clean_text": "The doctor is not confident about the diagnosis.", "category": -1},
#     {"clean_text": "The medication is not working as expected.", "category": -1},
#     {"clean_text": "The condition is not worsening.", "category": 1},
#     {"clean_text": "The treatment is not making a significant impact.", "category": -1},
#     {"clean_text": "The patient is not recovering quickly.", "category": -1},
#     {"clean_text": "The vaccine is not causing any adverse effects.", "category": 1},
#     {"clean_text": "The patient is not responding to the treatment.", "category": -1},
#     {"clean_text": "The hospital is not overcrowded.", "category": 1},
#     {"clean_text": "The nurse is not available to assist.", "category": -1},
#     {"clean_text": "The results are not improving over time.", "category": -1},
#     {"clean_text": "The therapy is not recommended for children.", "category": 0},
#     {"clean_text": "The patient is not in a stable condition.", "category": -1},
#     {"clean_text": "The test is not showing abnormal values.", "category": 1},
#     {"clean_text": "The operation is not considered high risk.", "category": 1},
#     {"clean_text": "The hospital staff is not cooperative.", "category": -1},
#     {"clean_text": "The machine is not calibrated properly.", "category": -1},
#     {"clean_text": "The medication is not approved by authorities.", "category": -1},
#     {"clean_text": "The patient is not feeling any discomfort.", "category": 1},
#     {"clean_text": "The new policy is not favorable for patients.", "category": -1},
#     {"clean_text": "The procedure is not painful.", "category": 1},
#     {"clean_text": "The symptoms are not worsening.", "category": 1},
#     {"clean_text": "The prescription is not being followed correctly.", "category": -1},
#     {"clean_text": "The recovery process is not going smoothly.", "category": -1},
#     {"clean_text": "The facility is not meeting cleanliness standards.", "category": -1},
#     {"clean_text": "The patient is not experiencing fever anymore.", "category": 1},
#     {"clean_text": "The treatment cost is not affordable for many.", "category": -1},
#     {"clean_text": "The procedure is not complicated.", "category": 1},
#     {"clean_text": "The operation is not scheduled for next week.", "category": 0},
#     {"clean_text": "The condition is not critical at this stage.", "category": 1},
#     {"clean_text": "The results are not showing clear improvement.", "category": -1},
#     {"clean_text": "The travel experience is enjoyable and memorable.", "category": 1},
#     {"clean_text": "The transportation is reliable and efficient.", "category": 1},
#     {"clean_text": "The tour guide is knowledgeable and friendly.", "category": 1},
#     {"clean_text": "The accommodation is comfortable and clean.", "category": 1},
#     {"clean_text": "The itinerary is well-planned and exciting.", "category": 1},
#     {"clean_text": "The food options are diverse and delicious.", "category": 1},
#     {"clean_text": "The weather is pleasant and ideal for travel.", "category": 1},
#     {"clean_text": "He isn't sad.", "category": 1},
#     {"clean_text": "The dish is flavorful and well-prepared.", "category": 1},
#     {"clean_text": "The service is prompt and courteous.", "category": 1},
#     {"clean_text": "The ingredients are fresh and high-quality.", "category": 1},
#     {"clean_text": "The portion size is generous and satisfying.", "category": 1},
#     {"clean_text": "The restaurant is clean and well-maintained.", "category": 1},
#     {"clean_text": "The menu is diverse and offers great options.", "category": 1},
#     {"clean_text": "The presentation is appealing and artistic.", "category": 1},
#     {"clean_text": "The taste is authentic and delicious.", "category": 1},
#     {"clean_text": "The medication is not available at the pharmacy.", "category": -1},
#     {"clean_text": "The patient is not experiencing any major complications.", "category": 1},
#     {"clean_text": "The recovery process is not aligned with the expected timeline.", "category": -1},
#     {"clean_text": "The software is not user-friendly.", "category": -1},
#     {"clean_text": "The device is not compatible with the latest update.", "category": -1},
#     {"clean_text": "The application is not consuming excessive resources.", "category": 1},
#     {"clean_text": "The bug is not affecting core functionalities.", "category": 1},
#     {"clean_text": "The installation guide is not included in the package.", "category": 0},
#     {"clean_text": "The internet connection is not stable.", "category": -1},
#     {"clean_text": "The website is not loading properly on mobile devices.", "category": -1},
#     {"clean_text": "The data is not encrypted during transmission.", "category": -1},
#     {"clean_text": "The assignment is not graded yet.", "category": 0},
#     {"clean_text": "The lecture is not scheduled for today.", "category": 0},
#     {"clean_text": "The textbook is not available in the library.", "category": -1},
#     {"clean_text": "The student is not understanding the concept clearly.", "category": -1},
#     {"clean_text": "The syllabus is not updated for this semester.", "category": -1},
#     {"clean_text": "The instructor is not responding to emails.", "category": -1},
#     {"clean_text": "The study material is not difficult to comprehend.", "category": 1},
#     {"clean_text": "The course is not mandatory for graduation.", "category": 0},
#     {"clean_text": "The air quality is not safe for outdoor activities.", "category": -1},
#     {"clean_text": "The river is not polluted in this region.", "category": 1},
#     {"clean_text": "The recycling program is not effective in reducing waste.", "category": -1},
#     {"clean_text": "The weather is not favorable for farming this season.", "category": -1},
#     {"clean_text": "The wildlife population is not decreasing significantly.", "category": 1},
#     {"clean_text": "The ecosystem is not recovering as expected.", "category": -1},
#     {"clean_text": "The company's revenue is not growing this quarter.", "category": -1},
#     {"clean_text": "The product is not meeting customer expectations.", "category": -1},
#     {"clean_text": "The sales team is not achieving its targets.", "category": -1},
#     {"clean_text": "The market conditions are not stable right now.", "category": 0},
#     {"clean_text": "The partnership is not beneficial for both parties.", "category": -1},
#     {"clean_text": "The investment is not generating good returns.", "category": -1},
#     {"clean_text": "The business is not experiencing any financial loss.", "category": 1},
#     {"clean_text": "The management is not making rash decisions.", "category": 1},
#     {"clean_text": "The food is not fresh anymore.", "category": -1},
#     {"clean_text": "The car is not starting this morning.", "category": -1},
#     {"clean_text": "The coffee is not too hot to drink.", "category": 1},
#     {"clean_text": "The meeting is not taking place today.", "category": 0},
#     {"clean_text": "The apartment is not available for rent.", "category": -1},
#     {"clean_text": "The roads are not busy during this time of the day.", "category": 1},
#     {"clean_text": "The clothes are not drying quickly in this weather.", "category": -1},
#     {"clean_text": "The electricity is not working in the living room.", "category": -1},
#     {"clean_text": "The team is not performing well this season.", "category": -1},
#     {"clean_text": "The player is not fit to participate in the match.", "category": -1},
#     {"clean_text": "The referee is not making biased decisions.", "category": 1},
#     {"clean_text": "The stadium is not crowded during weekdays.", "category": 1},
#     {"clean_text": "The practice session is not scheduled for today.", "category": 0},
#     {"clean_text": "The coach is not happy with the players' performance.", "category": -1},
#     {"clean_text": "The train is not arriving on time.", "category": -1},
#     {"clean_text": "The flight is not delayed this evening.", "category": 1},
#     {"clean_text": "The destination is not crowded during the winter.", "category": 1},
#     {"clean_text": "The hotel is not offering discounts for this season.", "category": 0},
#     {"clean_text": "The luggage is not lost during the transit.", "category": 1},
#     {"clean_text": "The travel agency is not responsive to inquiries.", "category": -1},
#     {"clean_text": "The wait time is reasonable and well-managed.", "category": 1},
#     {"clean_text": "The prices are affordable and reasonable.", "category": 1},
#     {"clean_text": "I don't think i feel happy", "category": -1},
#     {"clean_text": "I don't like it", "category": -1},
#     {"clean_text": "I don't like how this movie ended.", "category": -1},
#     {"clean_text": "I like the sound of the ocean.", "category": 1},
#     {"clean_text": "I don't like waking up early.", "category": -1},
#     {"clean_text": "I like to read before bed.", "category": 1},
#     {"clean_text": "I don't like the way he spoke to me.", "category": -1},
#     {"clean_text": "I like the convenience of online shopping.", "category": 1},
#     {"clean_text": "I don't like being rushed.", "category": -1},
#     {"clean_text": "I like how this song makes me feel.", "category": 1},
#     {"clean_text": "I don't like spicy food.", "category": -1},
#     {"clean_text": "I like the design of this app.", "category": 1},
#     {"clean_text": "I don't like rainy days.", "category": -1},
#     {"clean_text": "I like going for long walks in the park.", "category": 1},
#     {"clean_text": "I don't like the taste of coffee.", "category": -1},
#     {"clean_text": "I like trying new recipes.", "category": 1},
#     {"clean_text": "I don't like how crowded it gets on weekends.", "category": -1},
#     {"clean_text": "I like the feeling of fresh air.", "category": 1},
#     {"clean_text": "I like how it is", "category": 1},
#     {"clean_text": "I don't like the taste of this dish.", "category": -1},
#     {"clean_text": "I like how this dress fits.", "category": 1},
#     {"clean_text": "I don't like the color of this car.", "category": -1},
#     {"clean_text": "I like the service at this restaurant.", "category": 1},
#     {"clean_text": "He isn't sad about losing the game.", "category": 0},
#     {"clean_text": "He isn't sad because he prepared for this outcome.", "category": 1},
#     {"clean_text": "He isn't sad; he's relieved it finally ended.", "category": 1},
#     {"clean_text": "He isn't sad about the situation; he's frustrated instead.", "category": -1},
#     {"clean_text": "He isn't sad; he feels hopeful about the future.", "category": 1},
#     {"clean_text": "He isn't sad that he missed the event.", "category": 0},
#     {"clean_text": "He isn't sad, but he's disappointed with the results.", "category": -1},
#     {"clean_text": "He isn't sad about the breakup; he knew it was inevitable.", "category": 0},
#     {"clean_text": "He isn't sad about failing the test; he learned something new.", "category": 1},
#     {"clean_text": "He isn't sad about the situation, but he feels conflicted.", "category": 0},
#     {"clean_text": "He isn't sad at all; he's excited to move on.", "category": 1},
#     {"clean_text": "He isn't sad, just surprised by the news.", "category": 0},
#     {"clean_text": "He isn't sad; he is just confused about what happened.", "category": 0},
#     {"clean_text": "He isn't sad because he got what he deserved.", "category": 0},
#     {"clean_text": "He isn't sad about the loss; he feels indifferent.", "category": 0},
#     {"clean_text": "He isn't sad, but he's definitely not happy either.", "category": 0},
#     {"clean_text": "He isn't sad about his mistakes; he's trying to improve.", "category": 1},
#     {"clean_text": "He isn't sad that he lost his job; he already has a better offer.", "category": 1},
#     {"clean_text": "He isn't sad; he feels optimistic about his chances.", "category": 1},
#     {"clean_text": "He isn't sad; he doesn't even care anymore.", "category": -1},
#     {"clean_text": "He isn't sad, but he regrets his decision.", "category": -1},
#     {"clean_text": "He isn't sad about their fight; he feels it was necessary.", "category": 0},
#     {"clean_text": "He isn't sad; he's just focused on the next challenge.", "category": 1},
#     {"clean_text": "He isn't sad about losing friends; he values quality over quantity.", "category": 1},
#     {"clean_text": "He isn't sad about being alone; he enjoys the peace.", "category": 1},
#     {"clean_text": "He isn't sad, but he's overwhelmed by the situation.", "category": -1},
#     {"clean_text": "He isn't sad; he's grateful for the lessons learned.", "category": 1},
#     {"clean_text": "He isn't sad about the past; he looks forward to the future.", "category": 1},
#     {"clean_text": "He isn't sad; he feels proud of his achievements.", "category": 1},
#     {"clean_text": "He isn't sad, but he feels the pressure to do better.", "category": 0},
#     {"clean_text": "He isn't sad that he lost; he sees it as an opportunity to grow.", "category": 1},
#     {"clean_text": "He isn't sad about her absence; he feels at peace.", "category": 1},
#     {"clean_text": "He isn't sad; he's glad it happened the way it did.", "category": 1},
#     {"clean_text": "He isn't sad about the changes; he embraces them.", "category": 1},
#     {"clean_text": "He isn't sad; he's simply uncertain about the future.", "category": 0},
#     {"clean_text": "He isn't sad about failing; he learned something important.", "category": 1},
#     {"clean_text": "He isn't sad about losing his team; he feels they will understand.", "category": 1},
#     {"clean_text": "He isn't sad about his mistakes; he's learned to accept them.", "category": 1},
#     {"clean_text": "He isn't sad about the news; he thinks it's for the best.", "category": 1},
#     {"clean_text": "He isn't sad, but he's still processing what happened.", "category": 0},
#     {"clean_text": "He isn't sad that he left; he believes it was the right choice.", "category": 1},
#     {"clean_text": "He isn't sad about missing the opportunity; he knows another will come.", "category": 1},
#     {"clean_text": "He isn't sad; he's trying to focus on what truly matters.", "category": 1},
#     {"clean_text": "He isn't sad about their breakup; he feels it was mutual.", "category": 0},
#     {"clean_text": "He isn't sad about failing the test; he'll try again.", "category": 1},
#     {"clean_text": "He isn't sad, but he feels disappointed in himself.", "category": -1},
#     {"clean_text": "He isn't sad about the argument; he feels it cleared the air.", "category": 1},
#     {"clean_text": "He isn't sad about losing the election; he feels motivated to try again.", "category": 1},
#     {"clean_text": "He isn't sad that he didn't win; he feels proud of his efforts.", "category": 1},
#     {"clean_text": "He isn't sad; he knows it's part of life.", "category": 1},
#     {"clean_text": "I don't like crowded places.", "category": -1},
#     {"clean_text": "I like the way this product works.", "category": 1},
#     {"clean_text": "I don't like the noise in this area.", "category": -1},
#     {"clean_text": "The service isn't bad, but it could be better.", "category": 0},
#     {"clean_text": "The food isn't as fresh as I expected.", "category": -1},
#     {"clean_text": "I don't think I'll visit this restaurant again.", "category": -1},
#     {"clean_text": "The product isn't what was advertised, but it still works fine.", "category": 0},
#     {"clean_text": "The hotel isn't luxurious, but it's clean and comfortable.", "category": 1},
#     {"clean_text": "The staff didn't seem friendly during my stay.", "category": -1},
#     {"clean_text": "I don't feel the customer service was helpful at all.", "category": -1},
#     {"clean_text": "The phone isn't too expensive for its features.", "category": 1},
#     {"clean_text": "I didn't like the packaging; it felt cheap.", "category": -1},
#     {"clean_text": "The movie wasn't exciting, but it had a decent storyline.", "category": 0},
#     {"clean_text": "I can't say I enjoyed the experience.", "category": -1},
#     {"clean_text": "The app doesn't function as advertised.", "category": -1},
#     {"clean_text": "The shoes aren't the most comfortable, but they look good.", "category": 0},
#     {"clean_text": "I don't think the quality is worth the price.", "category": -1},
#     {"clean_text": "The laptop isn't bad for basic tasks.", "category": 1},
#     {"clean_text": "I didn't expect such quick delivery!", "category": 1},
#     {"clean_text": "The place wasn't crowded, which made it more enjoyable.", "category": 1},
#     {"clean_text": "The bed isn't too soft, but it's not uncomfortable either.", "category": 0},
#     {"clean_text": "I can't recommend this product to anyone.", "category": -1},
#     {"clean_text": "I don't believe this is the best option out there.", "category": -1},
#     {"clean_text": "The resort doesn't look like the photos online.", "category": -1},
#     {"clean_text": "I don't think the instructions are clear enough.", "category": -1},
#     {"clean_text": "The sound quality isn't great, but it's acceptable for the price.", "category": 0},
#     {"clean_text": "The service doesn't feel personal or attentive.", "category": -1},
#     {"clean_text": "I can't complain about the view; it was stunning.", "category": 1},
#     {"clean_text": "The book wasn't boring, but it lacked depth.", "category": 0},
#     {"clean_text": "I don't think the store has a good return policy.", "category": -1},
#     {"clean_text": "The phone isn't perfect, but it's good for casual use.", "category": 1},
#     {"clean_text": "I don't feel the staff cared about my concerns.", "category": -1},
#     {"clean_text": "The coffee isn't the best I've had, but it's okay.", "category": 0},
#     {"clean_text": "The website doesn't load properly on mobile.", "category": -1},
#     {"clean_text": "I didn't like the taste of the pasta.", "category": -1},
#     {"clean_text": "The product isn't poorly made, but it feels flimsy.", "category": 0},
#     {"clean_text": "The theater wasn't very clean, which was disappointing.", "category": -1},
#     {"clean_text": "I don't think this game is worth the hype.", "category": -1},
#     {"clean_text": "The car isn't fuel-efficient, but it's reliable.", "category": 1},
#     {"clean_text": "I don't feel the staff was rude, but they weren't very helpful.", "category": 0},
#     {"clean_text": "The hotel isn't the best I've stayed at, but it's decent for the price.", "category": 1},
#     {"clean_text": "The food truck didn't meet my expectations.", "category": -1},
#     {"clean_text": "I don't think the performance was worth the ticket price.", "category": -1},
#     {"clean_text": "The service isn't slow, but it's not fast either.", "category": 0},
#     {"clean_text": "The sofa doesn't feel sturdy enough for daily use.", "category": -1},
#     {"clean_text": "I can't say the atmosphere was welcoming.", "category": -1},
#     {"clean_text": "I didn't enjoy the design of the user interface.", "category": -1},
#     {"clean_text": "The movie doesn't have great acting, but the plot is strong.", "category": 1},
#     {"clean_text": "I don't feel the need to visit this place again.", "category": -1},
#     {"clean_text": "The bread isn't freshly baked, but it tastes fine.", "category": 0},
#     {"clean_text": "I can't say the lecture was engaging.", "category": -1},
#     {"clean_text": "The chair isn't uncomfortable, but it's not the best either.", "category": 0},
#     {"clean_text": "I don't think the value matches the price.", "category": -1},
#     {"clean_text": "The room wasn't as spacious as the pictures suggested.", "category": -1},
#     {"clean_text": "I don't feel this app is user-friendly at all.", "category": -1},
#     {"clean_text": "The event wasn't well-organized, but I had some fun.", "category": 0},
#     {"clean_text": "The coffee shop doesn't have enough seating.", "category": -1},
#     {"clean_text": "I didn't expect the delivery to arrive so quickly.", "category": 1},
#     {"clean_text": "The camera isn't high-quality, but it's affordable.", "category": 1},
#     {"clean_text": "The customer support didn't solve my issue.", "category": -1},
#     {"clean_text": "The fabric isn't soft, but it seems durable.", "category": 0},
#     {"clean_text": "I can't say I was impressed with the quality.", "category": -1},
#     {"clean_text": "The salad doesn't taste fresh, but the dressing is good.", "category": 0},
#     {"clean_text": "The menu isn't very diverse, but the dishes are delicious.", "category": 1},
#     {"clean_text": "I don't think I'll recommend this place to my friends.", "category": -1},
#     {"clean_text": "The staff isn't rude, but they aren't very attentive either.", "category": 0},
#     {"clean_text": "The delivery wasn't late, but it took longer than expected.", "category": 0},
#     {"clean_text": "I can't say the book is terrible, but it's not great either.", "category": 0},
#     {"clean_text": "The lighting in the room isn't bright enough.", "category": -1},
#     {"clean_text": "I don't believe the reviews accurately reflect the experience.", "category": -1},
#     {"clean_text": "The design isn't modern, but it's functional.", "category": 0},
#     {"clean_text": "I can't recommend this product; it broke after a week.", "category": -1},
#     {"clean_text": "The phone doesn't feel premium, but it works fine.", "category": 0},
#     {"clean_text": "I don't feel the need to replace my current device yet.", "category": 1},
#     {"clean_text": "The packaging isn't eco-friendly, which is disappointing.", "category": -1},
#     {"clean_text": "The experience wasn't bad, but I wouldn't do it again.", "category": 0},
#     {"clean_text": "I don't think the warranty terms are clear enough.", "category": -1},
#     {"clean_text": "The screen isn't very sharp, but it's usable for videos.", "category": 0},
#     {"clean_text": "The park isn't well-maintained, but it's a peaceful spot.", "category": 0},
#     {"clean_text": "The furniture doesn't look expensive, but it's sturdy.", "category": 1},
#     {"clean_text": "The wifi isn't fast, but it's good enough for browsing.", "category": 0},
#     {"clean_text": "I didn't expect the product to arrive damaged.", "category": -1},
#     {"clean_text": "The installation wasn't as straightforward as I hoped.", "category": -1},
#     {"clean_text": "I can't say I enjoyed the wait time for service.", "category": -1},
#     {"clean_text": "The ice cream shop doesn't have many flavors, but the ones they do have are great.", "category": 1},
#     {"clean_text": "I don't think the course content was explained well.", "category": -1},
#     {"clean_text": "The food isn't too spicy, which I liked.", "category": 1},
#     {"clean_text": "The shop doesn't have a return policy, which is inconvenient.", "category": -1},
#     {"clean_text": "The coat doesn't fit perfectly, but it's warm and cozy.", "category": 1},
#     {"clean_text": "I don't feel the subscription is worth the monthly cost.", "category": -1},
#     {"clean_text": "The movie isn't very realistic, but it's entertaining.", "category": 1},
#     {"clean_text": "The kitchen appliances don't seem durable.", "category": -1},
#     {"clean_text": "I can't say the pizza was amazing, but it wasn't bad either.", "category": 0},
#     {"clean_text": "The game doesn't have many levels, but it's fun to play.", "category": 1},
#     {"clean_text": "The road isn't smooth, which made the drive uncomfortable.", "category": -1},
#     {"clean_text": "I didn't find the staff to be knowledgeable about their menu.", "category": -1},
#     {"clean_text": "The shoes don't offer much arch support, but they look great.", "category": 0},
#     {"clean_text": "I can't recommend this airline; the seats were terrible.", "category": -1},
#     {"clean_text": "The movie theater wasn't very clean, but the sound system was great.", "category": 0},
#     {"clean_text": "The course material isn't very engaging, but it's comprehensive.", "category": 0},
#     {"clean_text": "I don't think the gift wrapping was worth the extra charge.", "category": -1},
#     {"clean_text": "I like spending time with my friends.", "category": 1},
#     {"clean_text": "He isn't sad about the results.", "category": 0},
#     {"clean_text": "He isn't just sad; he's heartbroken.", "category": -1},
#     {"clean_text": "He isn't sad; he feels relieved.", "category": 1},
#     {"clean_text": "He isn't sad, but he's not happy either.", "category": 0},
#     {"clean_text": "He isn't sad because he knew it was coming.", "category": 1},
#     {"clean_text": "He isn't sad; he is frustrated with the outcome.", "category": -1},
#     {"clean_text": "He isn't sad; he doesn't care anymore.", "category": -1},
#     {"clean_text": "He isn't sad, he's just tired.", "category": 0},
#     {"clean_text": "I don't like the new policy.", "category": -1},
#     {"clean_text": "The service was excellent and I truly enjoyed my meal.", "category": 1},
#     {"clean_text": "I'm really disappointed with the product quality.", "category": -1},
#     {"clean_text": "I appreciate the effort you put into this project.", "category": 1},
#     {"clean_text": "I'm not satisfied with the results of the experiment.", "category": -1},
#     {"clean_text": "This book was fascinating and kept me engaged.", "category": 1},
#     {"clean_text": "I had a terrible experience at that restaurant.", "category": -1},
#     {"clean_text": "The concert was amazing and exceeded my expectations.", "category": 1},
#     {"clean_text": "I regret buying this item; it doesn't work as advertised.", "category": -1},
#     {"clean_text": "The atmosphere at the event was welcoming and friendly.", "category": 1},
#     {"clean_text": "I'm frustrated with the slow customer service response.", "category": -1},
#     {"clean_text": "The new features on this platform are incredibly useful.", "category": 1},
#     {"clean_text": "I was let down by the lack of communication.", "category": -1},
#     {"clean_text": "This app makes my life so much easier!", "category": 1},
#     {"clean_text": "I feel disheartened by the lack of support from my team.", "category": -1},
#     {"clean_text": "The quality of the product is outstanding!", "category": 1},
#     {"clean_text": "I am unhappy with how things turned out.", "category": -1},
#     {"clean_text": "I like the atmosphere of this cafe.", "category": 1},
#     {"clean_text": "I am not sad", "category": 1},
#     {"clean_text": "I don't enjoy this kind of music.", "category": -1},
#     {"clean_text": "I do not like the way this product works.", "category": -1},
#     {"clean_text": "I don't think this is the right decision.", "category": -1},
#     {"clean_text": "I do not appreciate the lack of communication.", "category": -1},
#     {"clean_text": "I don't believe this is the best option available.", "category": -1},
#     {"clean_text": "I do not feel comfortable recommending this service.", "category": -1},
#     {"clean_text": "I don't think I will return to this restaurant.", "category": -1},
#     {"clean_text": "I do not find this movie entertaining.", "category": -1},
#     {"clean_text": "I don't feel that the price is justified.", "category": -1},
#     {"clean_text": "I do not enjoy spending time on this task.", "category": -1},
#     {"clean_text": "I don't see the value in this product.", "category": -1},
#     {"clean_text": "I do not think this plan will work.", "category": -1},
#     {"clean_text": "I don't have any issues with the service provided.", "category": 1},
#     {"clean_text": "I do not regret my decision to purchase this item.", "category": 1},
#     {"clean_text": "I don't believe there are any flaws in this design.", "category": 1},
#     {"clean_text": "Hi, I loved the service at your hotel!", "category": 1},
#     {"clean_text": "Hi, the product was damaged when it arrived.", "category": -1},
#     {"clean_text": "Hi, could you provide more details about this offer?", "category": 0},
#     {"clean_text": "Hi there, the room wasn't clean when we arrived.", "category": -1},
#     {"clean_text": "Hi, your support team resolved my issue quickly. Thanks!", "category": 1},
#     {"clean_text": "Hi, I need to cancel my order, but the process is unclear.", "category": 0},
#     {"clean_text": "Hi, the event was poorly organized, and I’m disappointed.", "category": -1},
#     {"clean_text": "Hi, everything went smoothly, and I’m very happy with the results.", "category": 1},
#     {"clean_text": "Hi, I can't believe how bad the customer service was.", "category": -1},
#     {"clean_text": "Hi, the food was delicious, and the staff was friendly.", "category": 1},
#     {"clean_text": "Hi there, can you help me with this issue?", "category": 0},
#     {"clean_text": "Hi, the package didn’t arrive on time, and I’m not satisfied.", "category": -1},
#     {"clean_text": "Hi, just wanted to let you know how amazing the experience was!", "category": 1},
#     {"clean_text": "Hi, the delivery was faster than I expected. Great job!", "category": 1},
#     {"clean_text": "Hi, I think there was a mistake with my order.", "category": 0},
#     {"clean_text": "Hi, I’m disappointed with the quality of the product.", "category": -1},
#     {"clean_text": "Hi, the instructions were clear and easy to follow.", "category": 1},
#     {"clean_text": "Hi, the app keeps crashing. Can you fix it?", "category": -1},
#     {"clean_text": "Hi there, thanks for the quick response to my query.", "category": 1},
#     {"clean_text": "Hi, I’d like to know if this feature is available.", "category": 0},
#     {"clean_text": "Hi, I can’t believe how amazing the staff was. Wonderful experience!", "category": 1},
#     {"clean_text": "Hi, I’m not happy with the way this issue was handled.", "category": -1},
#     {"clean_text": "Hi, your team was extremely helpful. I appreciate it!", "category": 1},
#     {"clean_text": "Hi, there was a problem with the payment process.", "category": 0},
#     {"clean_text": "Hi, I didn’t expect such a terrible experience at your store.", "category": -1},
#     {"clean_text": "Hi, thanks for the great service and attention to detail!", "category": 1},
#     {"clean_text": "Hi, the booking process was simple and straightforward.", "category": 1},
#     {"clean_text": "Hi, your website is not very user-friendly.", "category": -1},
#     {"clean_text": "Hi, I’d like to provide feedback about my recent purchase.", "category": 0},
#     {"clean_text": "Hi, I’m having trouble logging into my account. Can you help?", "category": -1},
#     {"clean_text": "Hi, I received excellent customer support. Thank you so much!", "category": 1},
#     {"clean_text": "Hi, I think there’s a bug in your system. Please check.", "category": 0},
#     {"clean_text": "Hi, I’m amazed at how quickly my issue was resolved.", "category": 1},
#     {"clean_text": "Hi, the service was slow, and the staff was rude.", "category": -1},
#     {"clean_text": "Hi, the app is great, but it could use some improvements.", "category": 0},
#     {"clean_text": "Hi, thank you for the follow-up on my request. Great job!", "category": 1},
#     {"clean_text": "Hi, I didn’t enjoy the experience at all. It was terrible.", "category": -1},
#     {"clean_text": "Hi, the product is exactly as described. I’m very satisfied.", "category": 1},
#     {"clean_text": "I do not feel any negative emotions towards this experience.", "category": 1},
#     {"clean_text": "I don't think the hotel is offering discounts for this season.", "category": 0},
#     {"clean_text": "I don't feel like the luggage is lost during the transit.", "category": 1},
#     {"clean_text": "Hi there, how are you doing?", "category": 0},
#     {"clean_text": "Hi, I just wanted to say thank you for your help.", "category": 1},
#     {"clean_text": "Hi, can you assist me with this issue?", "category": 0},
#     {"clean_text": "Hi, this is just a test message.", "category": 0},
#     {"clean_text": "I don't believe the travel agency is responsive to inquiries.", "category": -1},
#     {"clean_text": "I don't think the service at the hotel is satisfactory.", "category": 0},
#     {"clean_text": "I don't feel that my luggage is safe during the transit.", "category": 1},
#     {"clean_text": "I don't believe the travel agency provides good customer service.", "category": -1},
#     {"clean_text": "I don't see why the hotel is not offering better rates.", "category": 0},
#     {"clean_text": "I don't think the luggage is ever lost with this carrier.", "category": 1},
#     {"clean_text": "I don't find the travel agency helpful at all.", "category": -1},
#     {"clean_text": "I don't think the food was worth the price.", "category": -1},
#     {"clean_text": "I didn't find the staff helpful at all.", "category": -1},
#     {"clean_text": "The hotel is not as luxurious as advertised.", "category": -1},
#     {"clean_text": "I don't feel comfortable recommending this service.", "category": -1},
#     {"clean_text": "I can't say enough good things about the experience!", "category": 1},
#     {"clean_text": "The service wasn't bad, but it could be better.", "category": 0},
#     {"clean_text": "I never expected such an amazing outcome!", "category": 1},
#     {"clean_text": "They don't seem to care about customer feedback.", "category": -1},
#     {"clean_text": "I can't believe how fast the delivery was!", "category": 1},
#     {"clean_text": "I don't think I'll visit this place again.", "category": -1},
#     {"clean_text": "I didn't really enjoy the atmosphere.", "category": -1},
#     {"clean_text": "The product wasn't what I was looking for.", "category": -1},
#     {"clean_text": "I can't find a single flaw in their service.", "category": 1},
#     {"clean_text": "The package didn't arrive on time, but they apologized.", "category": 0},
#     {"clean_text": "I wouldn't recommend this to anyone.", "category": -1},
#     {"clean_text": "I wouldn't say it was terrible, just not great.", "category": 0},
#     {"clean_text": "The staff wasn't rude, but they weren't friendly either.", "category": 0},
#     {"clean_text": "I cannot express how much I loved the hotel!", "category": 1},
#     {"clean_text": "It isn't the worst experience, but far from the best.", "category": 0},
#     {"clean_text": "I don't regret buying this product at all!", "category": 1},
#     {"clean_text": "I can't say I hated it, but I didn't love it either.", "category": 0},
#     {"clean_text": "They didn't provide any support during my stay.", "category": -1},
#     {"clean_text": "I didn't expect such poor quality from a reputable brand.", "category": -1},
#     {"clean_text": "It wasn't exactly what I wanted, but it works.", "category": 0},
#     {"clean_text": "I can't believe they charged me for something I didn't order.", "category": -1},
#     {"clean_text": "I don't usually write reviews, but this was amazing!", "category": 1},
#     {"clean_text": "I didn't like the way the staff handled my complaint.", "category": -1},
#     {"clean_text": "The food wasn't just good; it was incredible!", "category": 1},
#     {"clean_text": "I don't think I've ever had a worse experience.", "category": -1},
#     {"clean_text": "I can't fault them for anything. Perfect service!", "category": 1},
#     {"clean_text": "The service isn't consistent, which is disappointing.", "category": -1},
#     {"clean_text": "I didn't expect much, but it was better than I thought.", "category": 1},
#     {"clean_text": "I can't recommend this enough. Simply outstanding!", "category": 1},
#     {"clean_text": "I never thought I'd leave such a negative review.", "category": -1},
#     {"clean_text": "I don't believe the hype; it’s overrated.", "category": -1},
#     {"clean_text": "I can’t think of anything they could’ve done better.", "category": 1},
#     {"clean_text": "The app doesn't work as expected. It's buggy.", "category": -1},
#     {"clean_text": "I don't think they care about customer satisfaction.", "category": -1},
#     {"clean_text": "I can't imagine a better vacation spot than this.", "category": 1},
#     {"clean_text": "It wasn't what I ordered, but they resolved it quickly.", "category": 0},
#     {"clean_text": "I don't feel the value matches the price.", "category": -1},
#     {"clean_text": "They didn't forget anything, and I’m impressed.", "category": 1},
#     {"clean_text": "I don't know how they could make it worse.", "category": -1},
#     {"clean_text": "I can't find anything bad to say about this service.", "category": 1},
#     {"clean_text": "I didn't notice any improvement after using the product.", "category": -1},
#     {"clean_text": "The movie wasn’t bad, but it wasn’t great either.", "category": 0},
#     {"clean_text": "I wouldn't hesitate to book with them again!", "category": 1},
#     {"clean_text": "I don't think they handled the situation professionally.", "category": -1},
#     {"clean_text": "I wouldn't trust them with my business again.", "category": -1},
#     {"clean_text": "I never thought I'd say this, but it was perfect.", "category": 1},
#     {"clean_text": "I can't understand how they got so many good reviews.", "category": -1},
#     {"clean_text": "I don't think I'll ever come back here.", "category": -1},
#     {"clean_text": "The package wasn't damaged, but the contents were missing.", "category": -1},
#     {"clean_text": "I didn't like the taste of the food; it felt bland.", "category": -1},
#     {"clean_text": "The website isn't user-friendly, and it's hard to navigate.", "category": -1},
#     {"clean_text": "I can't believe how poor the customer service was.", "category": -1},
#     {"clean_text": "The product didn't meet my expectations, but the delivery was fast.", "category": 0},
#     {"clean_text": "I can't recommend this hotel because the rooms were dirty.", "category": -1},
#     {"clean_text": "I wouldn't say the experience was terrible, but it was far from great.", "category": 0},
#     {"clean_text": "The price wasn't low, but the quality made up for it.", "category": 1},
#     {"clean_text": "I don't feel like the staff was properly trained.", "category": -1},
#     {"clean_text": "I can't find any reason to give this less than five stars!", "category": 1},
#     {"clean_text": "I wouldn't recommend this restaurant; the food was cold and tasteless.", "category": -1},
#     {"clean_text": "The app doesn't crash anymore, but it’s still slow.", "category": 0},
#     {"clean_text": "I don't think the delivery could be any slower.", "category": -1},
#     {"clean_text": "I can't explain how disappointed I am with this service.", "category": -1},
#     {"clean_text": "The flight wasn't delayed, which was a pleasant surprise.", "category": 1},
#     {"clean_text": "I don't see how anyone could rate this highly.", "category": -1},
#     {"clean_text": "I wouldn't mind visiting again if they improve the menu.", "category": 0},
#     {"clean_text": "I don't think the support team solved my problem effectively.", "category": -1},
#     {"clean_text": "It isn't often that I write reviews, but this deserves one.", "category": 1},
#     {"clean_text": "I don't like to leave negative reviews, but this was awful.", "category": -1},
#     {"clean_text": "The car rental wasn't as expensive as I thought it would be.", "category": 1},
#     {"clean_text": "I can't complain about the food, but the service was slow.", "category": 0},
#     {"clean_text": "I wouldn't say this is the best choice, but it’s decent.", "category": 0},
#     {"clean_text": "I never expected such a rude response from the manager.", "category": -1},
#     {"clean_text": "I don't think the packaging was adequate to prevent damage.", "category": -1},
#     {"clean_text": "I can't believe how amazing the spa treatment was!", "category": 1},
#     {"clean_text": "I didn't expect the product to last so long. Very durable!", "category": 1},
#     {"clean_text": "I can't imagine booking this place for a second time.", "category": -1},
#     {"clean_text": "The staff didn't seem enthusiastic, but they were polite.", "category": 0},
#     {"clean_text": "I wouldn't describe it as luxurious, but it was comfortable.", "category": 0},
#     {"clean_text": "I don't understand how they thought this design was acceptable.", "category": -1},
#     {"clean_text": "I never thought I'd be writing such a glowing review!", "category": 1},
#     {"clean_text": "I can't help but praise the team's attention to detail.", "category": 1},
#     {"clean_text": "The coffee wasn't too strong, which is just how I like it.", "category": 1},
#     {"clean_text": "I can't believe I paid so much for such poor quality.", "category": -1},
#     {"clean_text": "The instructions weren't clear, so assembly took forever.", "category": -1},
#     {"clean_text": "I don't think the service has improved since my last visit.", "category": -1},
#     {"clean_text": "I can't say it was a bad experience, but it wasn’t great.", "category": 0},
#     {"clean_text": "I don't think I could find a better place for this price!", "category": 1},
#     {"clean_text": "The staff wasn't as attentive as I expected for the price.", "category": -1},
#     {"clean_text": "I don't think the reviews are fair. It’s much better in person.", "category": 1},
#     {"clean_text": "I didn't feel welcome when I arrived at the front desk.", "category": -1},
#     {"clean_text": "I can't believe they overcharged me and refused a refund.", "category": -1},
#     {"clean_text": "I don't think the competition stands a chance against this brand.", "category": 1},
#     {"clean_text": "The performance isn't terrible, but it lags behind competitors.", "category": 0},
#     {"clean_text": "I never thought I'd leave such a bad review, but here it is.", "category": -1},
#     {"clean_text": "The upgrade isn't worth the extra cost, in my opinion.", "category": -1},
#     {"clean_text": "I can't understand why this product has so many positive reviews.", "category": -1},
#     {"clean_text": "I don't think the product is durable enough for heavy use.", "category": -1},
#     {"clean_text": "The repair service didn't take long, but it wasn’t cheap.", "category": 0},
#     {"clean_text": "I wouldn't buy this again unless they improve the formula.", "category": -1},
#     {"clean_text": "The phone isn't charging properly after just two months.", "category": -1},
#     {"clean_text": "I don't feel like I got my money's worth.", "category": -1},
#     {"clean_text": "The packaging was so sturdy, it took me 30 minutes to open it.", "category": -1},
#     {"clean_text": "Oh, just what I needed, another gadget that barely works.", "category": -1},
#     {"clean_text": "Sure, it's cheap, but it looks like it might fall apart any second.", "category": -1},
#     {"clean_text": "Great timing, it arrived a week late, just in time for nothing.", "category": -1},
#     {"clean_text": "It's not terrible, but I wouldn't recommend it either.", "category": 0},
#     {"clean_text": "Yeah, because everyone needs a toaster that burns toast evenly.", "category": -1},
#     {"clean_text": "I guess it does the job if you lower your expectations.", "category": 0},
#     {"clean_text": "The service was unforgettable—I'll never come back.", "category": -1},
#     {"clean_text": "Wow, I can't believe I waited so long to buy this!", "category": 1},
#     {"clean_text": "I can't believe how much I love this new gadget!", "category": 1},
#     {"clean_text": "The customer support is so 'helpful' they just kept me on hold for an hour.", "category": -1},
#     {"clean_text": "This chair is amazing—if you're a fan of back pain.", "category": -1},
#     {"clean_text": "It's really 'innovative' to ship a phone without a charger.", "category": -1},
#     {"clean_text": "I mean, who doesn't love a blender that leaks everywhere?", "category": -1},
#     {"clean_text": "The user manual is so clear, it's like solving a riddle every time.", "category": -1},
#     {"clean_text": "Oh, it's perfect—if you don't actually plan on using it.", "category": -1},
#     {"clean_text": "The speed of delivery was incredible, considering it took over a month.", "category": -1},
#     {"clean_text": "This is hands down the best purchase I've made in years.", "category": 1},
#     {"clean_text": "The quality is okay, but I expected a bit more for the price.", "category": 0},
#     {"clean_text": "Fantastic! It broke after just one use.", "category": -1},
#     {"clean_text": "The screen resolution is great, but only if you squint.", "category": -1},
#     {"clean_text": "Not bad, if you don't mind waiting forever for it to arrive.", "category": 0},
#     {"clean_text": "It's exactly what I needed. Couldn't ask for more.", "category": 1},
#     {"clean_text": "Such a premium experience—if paying more for less counts as premium.", "category": -1},
#     {"clean_text": "Finally, a product that matches its description perfectly.", "category": 1},
#     {"clean_text": "The feature set is 'impressive,' assuming you ignore the constant glitches.", "category": -1},
#     {"clean_text": "Can't believe how much I love this product! Totally worth it.", "category": 1},
#     {"clean_text": "Sure, it works... as long as you don't actually rely on it.", "category": -1},
#     {"clean_text": "Best purchase ever. I'm recommending it to all my friends.", "category": 1},
#     {"clean_text": "The sound quality is great, but the build feels like it's made of paper.", "category": 0},
#     {"clean_text": "Amazing craftsmanship—if duct tape counts as a material.", "category": -1},
#     {"clean_text": "The design is unique, in the way a three-legged chair is unique.", "category": -1},
#     {"clean_text": "Oh, the shipping was free, but at what cost?", "category": -1},
#     {"clean_text": "Couldn't be happier with how well this performs.", "category": 1},
#     {"clean_text": "Sure, it's lightweight. It also feels like it'll snap in half.", "category": -1},
#     {"clean_text": "The software updates are frequent, which is great, if only they fixed the actual problems.", "category": -1},
#     {"clean_text": "It’s not the worst product ever, but it’s definitely close.", "category": -1},
#     {"clean_text": "I was skeptical at first, but this turned out to be an amazing purchase.", "category": 1},
#     {"clean_text": "It would have been perfect, except for all the things wrong with it.", "category": -1},
#     {"clean_text": "The brightness of the display is stunning, especially when it doesn’t work outdoors.", "category": -1},
#     {"clean_text": "Everything about this screams luxury—except the quality.", "category": -1},
#     {"clean_text": "The material feels premium, and it's comfortable to use all day.", "category": 1},
#     {"clean_text": "Setup was so 'easy' I had to call tech support twice.", "category": -1},
#     {"clean_text": "Who knew that premium could feel so... cheap?", "category": -1},
#     {"clean_text": "Definitely exceeds expectations. Great product!", "category": 1},
#     {"clean_text": "The curtains aren't as vibrant as they appeared onlineL.", "category": -1},
#     {"clean_text": "The headphones don't fit well, but the sound quality is great.", "category": 0},
#     {"clean_text": "I don't know if I can trust this brand again.", "category": -1},
#     {"clean_text": "Hi, how are you?", "category": 0},
#     {"clean_text": "Hi there!", "category": 0},
#     {"clean_text": "Hi, it's nice to see you.", "category": 0},
#     {"clean_text": "Hi, can I help you?", "category": 0},
#     {"clean_text": "They didn't follow through on their promises to improve the service, which has led to growing frustration among customers", "category": -1},
#     {"clean_text": "Hi, what's up?", "category": 0},
#     {"clean_text": "Hi", "category": 0},
#     {"clean_text": "you nigga", "category": -1},
#     {"clean_text": "They promised to enhance the user experience, but the continued glitches have only resulted in more dissatisfaction among users.", "category": -1},
#     {"clean_text": "The management assured us that the issues would be resolved quickly, yet we still face the same problems, leading to widespread disappointment.", "category": -1},
#     {"clean_text": "Customers were told that the new features would be launched last month, but the delays have caused increasing annoyance and skepticism.", "category": -1},
#     {"clean_text": "The company claimed they would improve their response times, but the lack of progress has left many feeling ignored and frustrated.", "category": -1},
#     {"clean_text": "Despite their assurances to provide regular updates, the silence from the support team has left customers feeling abandoned and unhappy.", "category": -1},
#     {"clean_text": "They guaranteed a seamless transition to the new system, but the constant errors have created chaos, resulting in mounting frustration.", "category": -1},
#     {"clean_text": "Promises of better communication were made, yet the ongoing lack of information has led to a sense of distrust among clients.", "category": -1},
#     {"clean_text": "The team vowed to fix the recurring issues promptly, but their inaction has only fueled anger and dissatisfaction among users.", "category": -1},
#     {"clean_text": "Although they pledged to deliver exceptional service, the persistent problems have caused significant discontent among the clientele.", "category": -1},
#     {"clean_text": "They stated that improvements would be made based on customer feedback, but the failure to act has left many feeling unheard and frustrated.", "category": -1},
#     {"clean_text": "I can't describe how satisfying this purchase has been.", "category": 1}
# ])
#
# additional_data.to_csv("C:\\Users\\asus\\Downloads\\sentiment_analysis (mine).csv",index=False)
#
# df23=pd.read_csv("C:\\Users\\asus\\Downloads\\amazon_cells_labelled.txt",header=None,names=['clean_text','category'],sep='\t')
# df23['category']=df23['category'].replace({0:-1})
#
# df24=pd.read_csv("C:\\Users\\asus\\Downloads\\data 1_train.csv")
# df24=df24[[' text',' class']]
# df24=df24.rename(columns={' text':'clean_text'," class":"category"})
#
#
# df25=pd.read_csv("C:\\Users\\asus\\Downloads\\data 2_train.csv")
# df25=df25[[' text',' class']]
# df25=df25.rename(columns={' text':'clean_text'," class":"category"})
#
# neg_words=pd.read_csv("C:\\Users\\asus\\Downloads\\negative-words.txt",header=None,names=['clean_text'],sep='\t')
# neg_words['category']=-1
#
# pos_words=pd.read_csv("C:\\Users\\asus\\Downloads\\positive-words.txt",header=None,names=['clean_text'],sep='\t')
# pos_words['category']=1
#
# neg_sen=pd.read_csv("C:\\Users\\asus\\Downloads\\train-neg.txt",header=None,names=['clean_text'],sep='\t')
# neg_sen['category']=-1
#
# pos_sen=pd.read_csv("C:\\Users\\asus\\Downloads\\train-pos.txt",header=None,names=['clean_text'],sep='\t')
# pos_sen['category']=1
#
# df=pd.concat([df1,additional_data],ignore_index=True)
# # pd.set_option('display.max_rows', None)
# # pd.set_option('display.max_colwidth', None)
#
#
# df=df.drop_duplicates()
#
#
# df=df.dropna()
#
#
#
# df['category']=df['category'].astype(int)
#
# import re
#
#
# def preprocess_text(text):
#     text = text.lower()
#
#     text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
#
#     return text
#
#
# import re
#
#
# def handle_negation(text):
#     # List of negation patterns to handle
#     negation_patterns = [
#         # Handle multi-word negations (e.g., "not really", "not at all")
#         (
#         r'\b(not\s+really|not\s+at\s+all|not\s+exactly|not\s+so|not\s+very|not\s+too|not\s+much|not\s+any|not\s+quite)\b',
#         lambda match: "NOT_" + match.group(0).replace(" ", "_")),
#
#         # Handle "don't/doesn't/didn't + verb + object" (e.g., "I don't feel great")
#         (r"\b(don't|doesn't|didn't)\s+(think|believe|feel|hope|know)\s+([\w\s]+)",
#          lambda match: "NOT_" + match.group(2) + "_" + match.group(3).replace(" ", "_")),
#
#         # Handle auxiliary verbs + "not" + verb (e.g., "I do not want", "You did not see")
#         (r"\b(are|is|am|was|were|be|been|have|has|had)\s+not\s+(\w+)",
#          r"NOT_\2"),
#
#         # Handle general negations (e.g., "not happy", "never go")
#         (r"\b(not|no|never|n't|don't|doesn't|didn't|can't|won't|wouldn't|wasn't|isn't|aren't|hasn't|haven't)\s+(\w+)",
#          r"NOT_\2"),
#
#         # Handle double negatives (e.g., "I don't need no help")
#         (r"\b(no|not|never)\s+(.*?)(\bno\b|\bnot\b|\bnever\b)",
#          r"NOT_\2 NOT_\3"),
#
#         # Handle implicit negations (e.g., "hardly", "without", "any")
#         (r'\b(hardly|barely|scarcely|rarely|few|little|without|none|nobody|nothing|neither|nor|any)\b',
#          lambda match: "NOT_" + match.group(0)),
#
#         # Handle punctuation immediately after negations (e.g., "not!")
#         (r"\b(not|no|never|n't|don't|doesn't|didn't|can't|won't|wouldn't|isn't|aren't|hasn't|haven't)\b([^\w\s])",
#          r"NOT\2")
#     ]
#
#     # Apply all negation patterns
#     for pattern, replacement in negation_patterns:
#         text = re.sub(pattern, replacement, text)
#
#     # Replace spaces after 'NOT_' with underscores for consistent formatting
#     text = re.sub(r'NOT_(\S+)', lambda match: 'NOT_' + match.group(1).replace(" ", "_"), text)
#
#     return text
#
#
# from sklearn.naive_bayes import MultinomialNB
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score, classification_report
# from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.linear_model import LogisticRegression,LinearRegression
# from sklearn import svm
# from sklearn.pipeline import Pipeline
#
# x=df['clean_text'].apply(handle_negation)
# x=x.apply(preprocess_text)
# v=TfidfVectorizer(ngram_range=(1,2))
# model=svm.LinearSVC(class_weight="balanced")
# # pipeline = Pipeline([
# #     ('vectorizer', TfidfVectorizer()),
# #     ('classifier', svm.LinearSVC())
# # ])
#
# x=v.fit_transform(x)
# y=df['category'].to_numpy()
# x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=43,test_size=0.3)
# model.fit(x_train,y_train)
#
#
#
#
# # x_test=v.transform(df_test['text'])
# # y_test=df_test['label'].to_numpy()
# y_predict=model.predict(x_test)
#
#
# joblib.dump(model,"sentiment_analysis_model3.pkl")
# joblib.dump(v,"vectorizer3.pkl")












v=joblib.load("vectorizer2.pkl")
model=joblib.load("sentiment_analysis_model2.pkl")





def prediction(text):
    t=v.transform([text])
    res=model.predict(t)
    if res[0]==1:
        return "Postive"
    elif res[0]==0:
        return "Neutral"
    else: return "Negative"


